[package]
name = "linux-hs-elf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
object = "0.28.4"
clap = { version = "3.1.17", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
